@email = "admin@aeranerd.com"
@password = "motokob8q2p9"
@access_token = "eQ5YSeP1eHdRFPe17ZRJX7anUxAD2DUci5RvvMBsFLk4OpW0kzCEwXUPAyQaYxhU"

@pastaS3 = FESTIVALDOJAPAO2024

# @name autenticar
POST http://127.0.0.1:3001/api/login
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}}
}

###

@token = {{autenticar.response.body.$.access_token}}
#token = {{access_token}}

# @name registrar
POST http://127.0.0.1:3001/api/register
Content-Type: application/json

{
  "email": "brunodsstudio@gmail.com",
  "name": "Bruno",
  "password": "motokob8q2p9"
}
###
#@name materias
GET http://127.0.0.1:3001/api/materiasblza


###
#@name areas  
GET http://127.0.0.1:3001/api/areas

###
#@name writers
GET http://127.0.0.1:3001/api/writers

### ===================================
### 2. Buscar Galeria - Página 1 (padrão 25 itens)
### ===================================
GET http://127.0.0.1:3001/api/Galerias/{{pastaS3}}/1
Authorization: Bearer {{token}}
Accept: application/json

### ===================================
### 3. Buscar Galeria - Página 1 (10 itens por página)
### ===================================
GET http://127.0.0.1:3001/api/Galerias/{{pastaS3}}/1?quantidadePorPagina=10
Authorization: Bearer {{token}}
Accept: application/json



